services:
  postgres:
    image: postgres:16-alpine
    container_name: campusflow-postgres
    environment:
      POSTGRES_USER: campusflow
      POSTGRES_PASSWORD: campusflow_password
      POSTGRES_DB: campusflow_main
    ports:
      - "5432:5432"
    volumes:
      - campusflow_postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - campusflow-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: campusflow-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: campusflow
      RABBITMQ_DEFAULT_PASS: campusflow_password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - campusflow_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - campusflow-network

networks:
  campusflow-network:
    driver: bridge

volumes:
  campusflow_postgres_data:
  campusflow_rabbitmq_data:
